import type { Metadata } from "next";
import Link from "next/link";
import { CTA, PageHero, SectionTitle } from "@/components/ui";
import { SafeImage } from "@/components/safe-image";
export const metadata:Metadata={title:"من نحن",description:"تعرف على شركة زاد القوافل ورؤيتها وقيمها في مجال استيراد المواد الغذائية والمواشي واللحوم في ليبيا."};
export default function About(){return <>
<PageHero eyebrow="من نحن" title="رؤية تعرف الطريق." text="زاد القوافل شركة ليبية تعمل في استيراد المواد الغذائية والمواشي واللحوم، وتسعى إلى تطوير علاقات توريد موثوقة تربط بين المصادر المناسبة واحتياجات السوق الليبي." image="/images/cinematic/about-warehouse.webp" alt="مدير عمليات داخل مستودع حديث ومنظم للمواد الغذائية"/>
<section className="section"><div className="container prose-grid prose-grid--visual"><SectionTitle title="نربط المصدر بالسوق ضمن علاقة واضحة ومنظمة."/><div><p>انطلقت زاد القوافل من طرابلس برؤية تقوم على فهم احتياجات السوق، وبناء علاقات تجارية تتسم بالوضوح والمسؤولية والاستمرارية.</p><p>نعمل على تطوير شبكة من الموردين والشركاء في المجالات التي تخدم نشاط الشركة، مع الاهتمام باختيار الفرص المناسبة وبناء تعاون قابل للنمو على المدى الطويل.</p><p>لا ننظر إلى الاستيراد باعتباره عملية منفصلة، بل علاقة تبدأ بفهم الاحتياج، وتتطور عبر التنسيق والثقة بين الأطراف.</p><SafeImage src="/images/cinematic/vision-strategy.webp" alt="فريق إداري يراجع استراتيجية التوريد ومسارات المصادر" className="page-feature-image"/></div></div></section>
<section className="section sand"><div className="container vision-editorial"><SafeImage src="/images/warehouse.jpg" alt="عمليات مستودع زاد القوافل المنظمة" className="vision-editorial-image" position="50% 44%"/><div className="vision-statements"><article><span className="eyebrow">رؤيتنا</span><h2>شريك موثوق للسوق الليبي.</h2><p>أن تكون زاد القوافل شريكًا موثوقًا في استيراد وتوريد المواد الغذائية والمواشي واللحوم في السوق الليبي.</p></article><article><span className="eyebrow">رسالتنا</span><h2>علاقات توريد فعّالة وواضحة.</h2><p>بناء علاقات توريد فعالة مع مصادر مناسبة، وتقديم تجربة تعامل منظمة وواضحة تسهم في تلبية احتياجات السوق ودعم استمرارية التعاون بين الموردين والعملاء.</p></article></div></div></section>
<section className="section"><div className="container"><SectionTitle title="قيم تقود كل مسار."/><div className="values six">{[["الثقة","علاقات تقوم على الوضوح والالتزام المتبادل."],["التنظيم","منهج عمل يساعد على وضوح الخطوات والمسؤوليات."],["الاستمرارية","تعاون يهدف إلى بناء علاقات قابلة للنمو."],["الوضوح","تواصل مباشر ومعلومات واضحة بين جميع الأطراف."],["المسؤولية","تعامل مهني يراعي طبيعة النشاط ومتطلباته."],["الطموح","تطلع مستمر إلى تطوير الشبكة وتوسيع فرص التعاون."]].map(x=><article key={x[0]}><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></div></section>
<section className="section dark"><div className="container prose-grid"><SectionTitle title="زاد القوافل… اسم يحمل معنى الحركة والوصول."/><p>يجمع اسم زاد القوافل بين “الزاد” باعتباره رمزًا للاحتياج والوفرة، و“القوافل” باعتبارها رمزًا للحركة والتجارة واستمرار التواصل بين الأسواق. ومن هذا المعنى جاءت هوية تعبّر عن المسار، الرؤية، والوصول بثقة.</p></div></section>
<CTA title="تعرف على مجالات عملنا."><Link className="button" href="/business-areas">مجالات عملنا</Link></CTA></>}
