import Link from "next/link";
import { ArrowLink, CTA, SectionTitle } from "@/components/ui";
import { site } from "@/lib/site-config";

const areas=[
["01","استيراد المواد الغذائية","نعمل على استيراد مجموعة متنوعة من المواد والمنتجات الغذائية، من خلال التواصل مع مصادر وموردين يتناسبون مع طبيعة المنتجات واحتياجات السوق المستهدفة."],
["02","استيراد المواشي","تعمل الشركة على استيراد المواشي ضمن عمليات منظمة تراعي طبيعة النشاط ومتطلبات التنسيق بين الموردين والجهات المعنية واحتياجات السوق المحلي."],
["03","استيراد اللحوم","يشمل نشاط زاد القوافل استيراد اللحوم المبردة والمجمدة، مع الاهتمام باختيار المصادر المناسبة ومراعاة طبيعة الحفظ والتوريد."]
];
export default function Home(){
 return <>
 <section className="hero"><div className="container hero-grid"><div><span className="eyebrow light">زاد القوافل · طرابلس</span><h1>من المصدر إلى السوق، <em>مسار موثوق.</em></h1><p>زاد القوافل شركة ليبية متخصصة في استيراد المواد الغذائية والمواشي واللحوم، تعمل من طرابلس على بناء علاقات توريد منظمة تربط المصادر المناسبة باحتياجات السوق الليبي.</p><div className="button-row"><Link className="button" href="/business-areas">استكشف مجالاتنا</Link><Link className="button button--light" href="/contact">ابدأ التواصل</Link></div><a className="text-link-light" href={site.whatsapp}>تواصل عبر واتساب ←</a></div><div className="hero-mark"><img src="/icon.svg" alt="" aria-hidden="true"/></div></div></section>
 <section className="section"><div className="container split"><SectionTitle eyebrow="إمداد يتحرك بثقة" title="نربط احتياجات السوق بمصادر توريد مدروسة." text="تعمل زاد القوافل في قطاع الاستيراد والتوريد، انطلاقًا من فهم احتياجات السوق الليبي وبناء علاقات عمل واضحة مع الموردين والشركاء. نركز على التنظيم، جودة الاختيار، واستمرارية العلاقة من بداية التواصل وحتى وصول المنتجات إلى السوق."/><div className="brand-art"><img src="/icon.svg" alt="" aria-hidden="true"/><span>مسارٌ يبدأ بالفهم<br/>ويستمر بالثقة.</span></div><ArrowLink href="/about">تعرف على زاد القوافل</ArrowLink></div></section>
 <section className="section sand"><div className="container"><SectionTitle eyebrow="مجالات عملنا" title="ثلاثة مجالات ضمن رؤية توريد واحدة." text="نعمل في مجالات مترابطة تستجيب لاحتياجات السوق، مع التعامل مع طبيعة كل منتج ومتطلباته بصورة مستقلة ومدروسة."/><div className="areas">{areas.map((a)=><article className="area" key={a[0]}><span>{a[0]}</span><div><h3>{a[1]}</h3><p>{a[2]}</p><ArrowLink href="/business-areas">استكشف المجال</ArrowLink></div><b aria-hidden="true">←</b></article>)}</div></div></section>
 <section className="section dark"><div className="container"><SectionTitle eyebrow="مسار واضح" title="كل علاقة ناجحة تبدأ بفهم الاحتياج." text="ننظر إلى التوريد باعتباره علاقة مستمرة تقوم على وضوح المتطلبات، اختيار المصدر المناسب، والمتابعة المنظمة بين جميع الأطراف."/><ol className="steps">{[["فهم الاحتياج","تحديد طبيعة المنتج والكميات والمتطلبات الأساسية."],["دراسة المصدر","مراجعة خيارات الموردين ومدى ملاءمتها لاحتياجات السوق."],["تنسيق التوريد","تنظيم التواصل والمتطلبات بين الأطراف ذات العلاقة."],["استمرارية العلاقة","بناء تعاون واضح وقابل للتطور مع الموردين والعملاء."]].map((x,i)=><li key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></li>)}</ol></div></section>
 <section className="section"><div className="container"><SectionTitle title="شراكة تُبنى على الوضوح والثقة."/><div className="values">{[["فهم السوق المحلي","نبدأ من قراءة الاحتياجات الفعلية للسوق الليبي وطبيعة الطلب داخله."],["اختيار مدروس","نتعامل مع خيارات التوريد وفق طبيعة كل منتج ومتطلبات التعاون."],["وضوح في التعامل","نعتمد تواصلًا مباشرًا ومنظمًا يساعد جميع الأطراف على فهم المتطلبات."],["علاقات طويلة الأمد","نبحث عن تعاون قابل للاستمرار والتوسع، لا عن معاملات مؤقتة فقط."]].map(x=><article key={x[0]}><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></div></section>
 <section className="partnership-band"><div className="container"><SectionTitle eyebrow="الشراكات والتوريد" title="نبني علاقات تتجاوز حدود الأسواق." text="ترحب زاد القوافل بالتعاون مع المنتجين والمصانع والموردين والشركات التجارية الباحثة عن شريك في السوق الليبي، ضمن علاقات تقوم على وضوح التعامل، ملاءمة المنتجات، واستمرارية التوريد."/><div className="button-row"><Link className="button" href="/partnerships">ناقش فرصة تعاون</Link><a className="button button--light" href={`mailto:${site.emails.suppliers}`}>تواصل مع قسم الموردين</a></div></div></section>
 <CTA title="لنفتح مسارًا جديدًا للتعاون." text="تواصل مع فريق زاد القوافل لمناقشة طلب توريد، فرصة شراكة، أو تقديم منتجاتك للسوق الليبي."><Link className="button" href="/contact">تواصل معنا</Link><a className="button button--outline-dark" href={site.whatsapp}>واتساب</a><a className="arrow-link" href={site.phoneHref}>اتصل الآن ←</a></CTA>
 </>;
}
