import type { Metadata } from "next";
import { PageHero, SectionTitle } from "@/components/ui";
import { SafeImage } from "@/components/safe-image";
import { site } from "@/lib/site-config";
export const metadata:Metadata={title:"الشراكات والتوريد",description:"فرص التعاون مع زاد القوافل للموردين والمصانع والمنتجين والشركات الراغبة في الوصول إلى السوق الليبي."};
const foundations=[["وضوح المنتجات","معلومات واضحة عن المنتجات والمواصفات والقدرة على التوريد."],["استمرارية الإمداد","قدرة عملية على بناء تعاون مستمر، وليس طلبًا مؤقتًا فقط."],["ملاءمة السوق","منتجات وفرص تتناسب مع طبيعة الاحتياج داخل السوق الليبي."],["تواصل مهني","استجابة واضحة وتنظيم يساعدان على تقدم العلاقة بين الأطراف."]];
const process=[["إرسال المعلومات","مشاركة نبذة عن الشركة والمنتجات أو فرصة التعاون."],["مراجعة الفرصة","دراسة المعلومات ومدى ملاءمتها لمجالات عمل زاد القوافل."],["التواصل المباشر","مناقشة التفاصيل والمتطلبات الأساسية بين الأطراف."],["تطوير العلاقة","الانتقال إلى خطوات تعاون أكثر تحديدًا عند وجود توافق مناسب."]];
export default function Partnerships(){return <>
<PageHero eyebrow="الشراكات والتوريد" title="نبني علاقات تتجاوز حدود الأسواق." text="ترحب زاد القوافل بفرص التعاون مع المنتجين والمصانع والموردين والشركات التجارية الراغبة في الوصول إلى السوق الليبي أو تطوير علاقات توريد داخله." image="/images/cinematic/supplier-review.webp" alt="مراجعة عينات غذائية ووثائق توريد بين مورد وشريك تجاري"/>
<section className="section"><div className="container partnership-overview"><div><SectionTitle title="شراكات متنوعة ضمن رؤية واضحة."/><div className="tag-list">{["المنتجون والمصانع","موردو المواد الغذائية","شركات ومزارع توريد المواشي","موردو اللحوم المبردة والمجمدة","التجار والموزعون","جهات تبحث عن حلول توريد مناسبة للسوق الليبي"].map(x=><span key={x}>{x}</span>)}</div></div><SafeImage src="/images/partnerships.jpg" alt="اجتماع تجاري لمناقشة فرص الشراكة والتوريد" className="partnership-overview-image"/></div></section>
<section className="section sand"><div className="container"><SectionTitle title="أساس العلاقة الناجحة."/><div className="foundation-grid">{foundations.map((x,i)=><article key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></div></section>
<section className="section dark partnership-process"><div className="container process-layout"><SafeImage src="/images/cinematic/shipment-handover.webp" alt="فريق لوجستي يراجع تسليم شحنة مبردة منظمة" className="process-image"/><div><SectionTitle title="من التعارف إلى فرصة تعاون واضحة."/><ol className="process-list">{process.map((x,i)=><li key={x[0]}><span>0{i+1}</span><div><h3>{x[0]}</h3><p>{x[1]}</p></div></li>)}</ol></div></div></section>
<section className="section"><div className="container two-panels commercial-panels"><article><h2>هل تمثل مصنعًا أو جهة توريد؟</h2><p>أرسل معلومات شركتك، قائمة المنتجات، بلد المنشأ، والقدرة المتاحة للتوريد إلى فريق الموردين.</p><a className="button" href={`mailto:${site.emails.suppliers}`}>راسل قسم الموردين</a></article><article><h2>للفرص التجارية والشراكات</h2><p>للتعاون التجاري أو مناقشة فرصة شراكة، تواصل مباشرة مع قسم الشراكات.</p><a className="button" href={`mailto:${site.emails.partnerships}`}>راسل قسم الشراكات</a></article></div></section>
</>}
